### ISSUE TITLE
Request to increase the size limit for submission

### ISSUE THREAD

**Issue by mramezani64** [hilti-challenge/Hilti-SLAM-Challenge-2022#17]
Hi. Thank you for organising this great challenge.
Would it be possible to increase the maximum size for submission from 10MB to 20MB?
Currently, we receive a "too large file" error avoiding us to submit our file.

**Comment by hilti-challenge** [comment]
done!

**Comment by mramezani64** [comment]
> done!

Thanks for your reply. The error still persists: `The file is too large. Allowed maximum size is 10 MB.`

**Comment by hilti-challenge** [comment]
could you try again now? If it still fails please send the files via email to michael.helmberger@hilti.com
